// scripts/design-catalog.mjs tarafından üretilir.
export const studioCovers = {
  citrus: {
    ...{
      label: "Limonlu bir pazar",
      category: "Akşam yemeği",
      color: "#F9F1C9",
      text: "#164F36",
      font: "serif",
      caption: "Sofrada buluşalım.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/citrus.png"),
  },
  ribbon: {
    ...{
      label: "Mavi bir dilek",
      category: "Doğum günü",
      color: "#DDE9F8",
      text: "#173D74",
      font: "serif",
      caption: "İyi ki doğdun.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/ribbon.png"),
  },
  disco: {
    ...{
      label: "Gece bizim",
      category: "Ev partisi",
      color: "#4F25B6",
      text: "#FFFFFF",
      font: "bold",
      caption: "Bir gece. Bin anı.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/disco.png"),
  },
  chess: {
    ...{
      label: "Bir dilim mutluluk",
      category: "Doğum günü",
      color: "#FFF1E5",
      text: "#B33147",
      font: "bold",
      caption: "Mumları birlikte üfleyelim.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/chess.png"),
  },
  olive: {
    ...{
      label: "Zeytin dalı",
      category: "Düğün",
      color: "#F4F0E5",
      text: "#394A37",
      font: "serif",
      caption: "Hikâyemize ortak ol.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/olive.png"),
  },
  cobalt: {
    ...{
      label: "Mavi sofra",
      category: "Akşam yemeği",
      color: "#F5F1DD",
      text: "#1540A1",
      font: "serif",
      caption: "Muhabbetin en güzeli.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/cobalt.png"),
  },
  sunset: {
    ...{
      label: "Gün batımı kulübü",
      category: "Buluşma",
      color: "#F9673C",
      text: "#542316",
      font: "bold",
      caption: "Güneşi birlikte uğurlayalım.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/sunset.png"),
  },
  flower: {
    ...{
      label: "Papatya günleri",
      category: "Baby shower",
      color: "#F2CAD8",
      text: "#873450",
      font: "serif",
      caption: "Küçücük bir mutluluk.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/flower.png"),
  },
  film: {
    ...{
      label: "Mezunlar kulübü",
      category: "Mezuniyet",
      color: "#E3F36D",
      text: "#252823",
      font: "bold",
      caption: "Bir devrin en güzel sonu.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/film.png"),
  },
  arch: {
    ...{
      label: "Sade bir evet",
      category: "Düğün",
      color: "#EEDFD0",
      text: "#654D41",
      font: "serif",
      caption: "Sonsuza bir adım.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/arch.png"),
  },
  henna: {
    ...{
      label: "Kına kırmızısı",
      category: "Kına gecesi",
      color: "#651F35",
      text: "#FCE3B1",
      font: "serif",
      caption: "Bu gece bizden.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/henna.png"),
  },
  moon: {
    ...{
      label: "Ay ışığında",
      category: "İftar",
      color: "#142C41",
      text: "#F5E5B7",
      font: "serif",
      caption: "Aynı sofrada, aynı duada.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/moon.png"),
  },
  nazar: {
    ...{
      label: "Mavi maşallah",
      category: "Sünnet",
      color: "#B2D7F2",
      text: "#164DA0",
      font: "serif",
      caption: "Güzel bir güne buyrun.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/nazar.png"),
  },
  wheat: {
    ...{
      label: "Bereket zamanı",
      category: "Diş buğdayı",
      color: "#F7EACF",
      text: "#715028",
      font: "serif",
      caption: "İlk dişe kocaman bir kutlama.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/wheat.png"),
  },
  rose: {
    ...{
      label: "Gül bahçesi",
      category: "Mevlid",
      color: "#ECDCD1",
      text: "#69453D",
      font: "serif",
      caption: "Duada bir aradayız.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/rose.png"),
  },
  flag: {
    ...{
      label: "Yolun açık olsun",
      category: "Asker uğurlaması",
      color: "#E5EBDE",
      text: "#324838",
      font: "bold",
      caption: "Güle güle git, güle güle gel.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/flag.png"),
  },
  home: {
    ...{
      label: "Yeni ev, yeni anılar",
      category: "Ev partisi",
      color: "#EDCDA6",
      text: "#B24031",
      font: "serif",
      caption: "Kapımız sevdiklerimize açık.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/home.png"),
  },
  picnic: {
    ...{
      label: "Çimenlere serilelim",
      category: "Buluşma",
      color: "#EFF0CE",
      text: "#4D6036",
      font: "serif",
      caption: "Bir pazar bahanesi.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/picnic.png"),
  },
  cloud: {
    ...{
      label: "Bulutların üstünde",
      category: "Cinsiyet partisi",
      color: "#DFDBF5",
      text: "#615294",
      font: "serif",
      caption: "Bir sürprizimiz var.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/cloud.png"),
  },
  pink: {
    ...{
      label: "Pembe bir gece",
      category: "Bekârlığa veda",
      color: "#FBAECB",
      text: "#772453",
      font: "bold",
      caption: "En yakınlar. En güzel gece.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/pink.png"),
  },
  paper: {
    ...{
      label: "Bir kahve arası",
      category: "Buluşma",
      color: "#EDE4CE",
      text: "#3D342B",
      font: "serif",
      caption: "Hadi bir kahve içelim.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/paper.png"),
  },
  neon: {
    ...{
      label: "Son ders: eğlenmek",
      category: "Mezuniyet",
      color: "#202639",
      text: "#DFFF7C",
      font: "bold",
      caption: "Yeni başlangıçlara!",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/neon.png"),
  },
  welcomeback: {
    ...{
      label: "Yine bir aradayız",
      category: "Askerden dönüş",
      color: "#EFE2CF",
      text: "#594230",
      font: "serif",
      caption: "Hoş geldin. Çok özledik.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/welcomeback.png"),
  },
  journey: {
    ...{
      label: "Hayırlı yolculuk",
      category: "Hac uğurlaması",
      color: "#DFE8DC",
      text: "#395448",
      font: "serif",
      caption: "Dualarla yola çıkarken.",
      collection: "İllüstrasyon",
    },
    image: require("../../assets/studio/journey.png"),
  },
  "photo-sunnet-1": {
    ...{
      label: "Dala asılı mavi nazar boncukları",
      category: "Sünnet",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Sünnet için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-sunnet-1.jpg"),
  },
  "photo-sunnet-2": {
    ...{
      label: "Nazar boncuğu ağacı",
      category: "Sünnet",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Sünnet için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-sunnet-2.jpg"),
  },
  "photo-sunnet-3": {
    ...{
      label: "Tek büyük nazar boncuğu",
      category: "Sünnet",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Sünnet için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-sunnet-3.jpg"),
  },
  "photo-sunnet-4": {
    ...{
      label: "Nazar boncuklarıyla süslü ağaç",
      category: "Sünnet",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Sünnet için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-sunnet-4.jpg"),
  },
  "photo-kina-1": {
    ...{
      label: "Kına tepsisini andıran mumlu kâse",
      category: "Kına gecesi",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Kına gecesi için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-kina-1.jpg"),
  },
  "photo-kina-2": {
    ...{
      label: "Sıcak ışıkta iki mum",
      category: "Kına gecesi",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Kına gecesi için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-kina-2.jpg"),
  },
  "photo-kina-3": {
    ...{
      label: "Kırmızı işlemeli örtü",
      category: "Kına gecesi",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Kına gecesi için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-kina-3.jpg"),
  },
  "photo-bekarlik-1": {
    ...{
      label: "Pembe konfeti",
      category: "Bekârlığa veda",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Bekârlığa veda için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-bekarlik-1.jpg"),
  },
  "photo-bekarlik-2": {
    ...{
      label: "Gökyüzünde uçuşan konfeti",
      category: "Bekârlığa veda",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Bekârlığa veda için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-bekarlik-2.jpg"),
  },
  "photo-bekarlik-3": {
    ...{
      label: "Disko topu",
      category: "Bekârlığa veda",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Bekârlığa veda için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-bekarlik-3.jpg"),
  },
  "photo-bekarlik-4": {
    ...{
      label: "Deniz manzarasında iki kadeh",
      category: "Bekârlığa veda",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Bekârlığa veda için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-bekarlik-4.jpg"),
  },
  "photo-babyshower-1": {
    ...{
      label: "İnciler arasında bebek ayakkabıları",
      category: "Baby shower",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Baby shower için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-babyshower-1.jpg"),
  },
  "photo-babyshower-2": {
    ...{
      label: "Beyaz bebek ayakkabıları",
      category: "Baby shower",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Baby shower için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-babyshower-2.jpg"),
  },
  "photo-babyshower-3": {
    ...{
      label: "Pembe örgü patikler",
      category: "Baby shower",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Baby shower için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-babyshower-3.jpg"),
  },
  "photo-cinsiyet-1": {
    ...{
      label: "Gökyüzüne bırakılan renkli balonlar",
      category: "Cinsiyet partisi",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Cinsiyet partisi için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-cinsiyet-1.jpg"),
  },
  "photo-cinsiyet-2": {
    ...{
      label: "Pastel renkli küçük balonlar",
      category: "Cinsiyet partisi",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Cinsiyet partisi için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-cinsiyet-2.jpg"),
  },
  "photo-cinsiyet-3": {
    ...{
      label: "Kremalı kekler",
      category: "Cinsiyet partisi",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Cinsiyet partisi için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-cinsiyet-3.jpg"),
  },
  "photo-disbugdayi-1": {
    ...{
      label: "Buğday taneleri",
      category: "Diş buğdayı",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Diş buğdayı için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-disbugdayi-1.jpg"),
  },
  "photo-disbugdayi-2": {
    ...{
      label: "Altın rengi buğday başağı",
      category: "Diş buğdayı",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Diş buğdayı için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-disbugdayi-2.jpg"),
  },
  "photo-disbugdayi-3": {
    ...{
      label: "Bereketin simgesi nar",
      category: "Diş buğdayı",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Diş buğdayı için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-disbugdayi-3.jpg"),
  },
  "photo-dogumgunu-1": {
    ...{
      label: "Mumları yanan çikolatalı pasta",
      category: "Doğum günü",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Doğum günü için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-dogumgunu-1.jpg"),
  },
  "photo-dogumgunu-2": {
    ...{
      label: "Çilekli beyaz pasta ve mum",
      category: "Doğum günü",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Doğum günü için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-dogumgunu-2.jpg"),
  },
  "photo-dogumgunu-3": {
    ...{
      label: "Mumlu çikolatalı kek",
      category: "Doğum günü",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Doğum günü için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-dogumgunu-3.jpg"),
  },
  "photo-mevlid-1": {
    ...{
      label: "Kırmızı güller",
      category: "Mevlid",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Mevlid için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-mevlid-1.jpg"),
  },
  "photo-mevlid-2": {
    ...{
      label: "Pembe ve beyaz güller",
      category: "Mevlid",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Mevlid için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-mevlid-2.jpg"),
  },
  "photo-mevlid-3": {
    ...{
      label: "Cami avizesi",
      category: "Mevlid",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Mevlid için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-mevlid-3.jpg"),
  },
  "photo-iftar-1": {
    ...{
      label: "Kâsede hurma",
      category: "İftar",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "İftar için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-iftar-1.jpg"),
  },
  "photo-iftar-2": {
    ...{
      label: "Mum ışığında fener",
      category: "İftar",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "İftar için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-iftar-2.jpg"),
  },
  "photo-iftar-3": {
    ...{
      label: "Tepside hurmalar",
      category: "İftar",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "İftar için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-iftar-3.jpg"),
  },
  "photo-hac-1": {
    ...{
      label: "Gece Kâbe",
      category: "Hac uğurlaması",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Hac uğurlaması için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-hac-1.jpg"),
  },
  "photo-hac-2": {
    ...{
      label: "Kâbe ve Mescid-i Haram",
      category: "Hac uğurlaması",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Hac uğurlaması için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-hac-2.jpg"),
  },
  "photo-hac-3": {
    ...{
      label: "Tarihî seccade",
      category: "Hac uğurlaması",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Hac uğurlaması için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-hac-3.jpg"),
  },
  "photo-evpartisi-1": {
    ...{
      label: "Avuçta yeni evin anahtarları",
      category: "Ev partisi",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Ev partisi için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-evpartisi-1.jpg"),
  },
  "photo-evpartisi-2": {
    ...{
      label: "Aydınlık oturma odası",
      category: "Ev partisi",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Ev partisi için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-evpartisi-2.jpg"),
  },
  "photo-evpartisi-3": {
    ...{
      label: "Saksıda üç çiçek",
      category: "Ev partisi",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Ev partisi için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-evpartisi-3.jpg"),
  },
  "photo-yemek-1": {
    ...{
      label: "Şiş ve mezeler",
      category: "Akşam yemeği",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Akşam yemeği için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-yemek-1.jpg"),
  },
  "photo-yemek-2": {
    ...{
      label: "Kurulmuş uzun davet sofrası",
      category: "Akşam yemeği",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Akşam yemeği için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-yemek-2.jpg"),
  },
  "photo-yemek-3": {
    ...{
      label: "Çiçekli akşam sofrası",
      category: "Akşam yemeği",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Akşam yemeği için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-yemek-3.jpg"),
  },
  "photo-mezuniyet-1": {
    ...{
      label: "Mezuniyet kepleri",
      category: "Mezuniyet",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Mezuniyet için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-mezuniyet-1.jpg"),
  },
  "photo-mezuniyet-2": {
    ...{
      label: "Sayfaları açılan kitap",
      category: "Mezuniyet",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Mezuniyet için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-mezuniyet-2.jpg"),
  },
  "photo-mezuniyet-3": {
    ...{
      label: "Rafta eski kitaplar",
      category: "Mezuniyet",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Mezuniyet için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-mezuniyet-3.jpg"),
  },
  "photo-asker-1": {
    ...{
      label: "Boğaz'da dalgalanan Türk bayrağı",
      category: "Asker uğurlaması",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Asker uğurlaması için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-asker-1.jpg"),
  },
  "photo-asker-2": {
    ...{
      label: "Mavi gökyüzünde Türk bayrağı",
      category: "Asker uğurlaması",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Asker uğurlaması için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-asker-2.jpg"),
  },
  "photo-asker-3": {
    ...{
      label: "Ay yıldız",
      category: "Asker uğurlaması",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Asker uğurlaması için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-asker-3.jpg"),
  },
  "photo-bulusma-3": {
    ...{
      label: "Gün batımında bir bardak çay",
      category: "Buluşma",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Buluşma için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-bulusma-3.jpg"),
  },
  "photo-bulusma-1": {
    ...{
      label: "Ahşap masada kahve",
      category: "Buluşma",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Buluşma için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-bulusma-1.jpg"),
  },
  "photo-bulusma-2": {
    ...{
      label: "Piknik sepeti",
      category: "Buluşma",
      color: "#39362F",
      text: "#FFFFFF",
      font: "serif",
      caption: "Buluşma için buyrun.",
      collection: "Fotoğraf",
    },
    image: require("../../assets/studio/photo-bulusma-2.jpg"),
  },
};
