import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:3001';
if(!['localhost','127.0.0.1'].includes(new URL(base).hostname))throw new Error('Only local test servers are permitted.');
let checks=0;
async function req(path,method='GET',body,status=200){const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();assert.equal(r.status,status,JSON.stringify(data));checks++;return data}
const payload={title:'Pazar soframız',category:'Akşam yemeği',hostName:'Deneme Ev Sahibi',date:'2027-04-25',time:'17:00',venue:'Deneme Bahçesi',address:'',description:'Bu davet otomatik kontrol için oluşturuldu.',coverId:'citrus',coverData:null,capacity:20};
const a=await req('/api/mobile/events','POST',payload,201),b=await req('/api/mobile/events','POST',{...payload,title:'Diğer deneme daveti'},201);
const host='/api/mobile/events/'+a.manageToken+'/social',pub='/api/mobile/invites/'+a.inviteToken;
const settings={questions:[{id:'q1',prompt:'Bir şarkı önerir misin?'}],announcements:[{id:'a1',text:'Bahçede buluşuyoruz.',at:new Date().toISOString()}],poll:{id:'p1',title:'Ne zaman buluşalım?',closed:false,options:[{id:'sat',label:'Cumartesi 18.00'},{id:'sun',label:'Pazar 17.00'}]}};
const initial=await req(host);assert.equal(initial.version,0);
await req(host,'PATCH',{settings,version:0});
await req(host,'PATCH',{settings,version:0},409);
await req(host,'PATCH',{settings:{...settings,poll:{...settings.poll,options:[{id:'a',label:'A'},{id:'a',label:'B'}]}},version:1},400);
const g=await req(pub,'POST',{name:'Deneme Misafiri',status:'going',count:2,note:''});
const outsider=await req('/api/mobile/invites/'+b.inviteToken,'POST',{name:'Diğer Davetli',status:'going',count:1,note:''});
await req(pub+'/social','POST',{guestToken:outsider.token,pollId:'p1',votes:['sat'],answers:{}},404);
await req(pub+'/social','POST',{pollId:'p1',votes:['sat'],answers:{}},401);
let own=await req(pub+'/social','POST',{guestToken:g.token,pollId:'p1',votes:['sun','sun'],answers:{q1:'Deneme şarkı yanıtı'}});assert.equal(own.totals.sun,1);assert.equal(own.voters,1);
let publicData=await req(pub+'/social');assert.equal(publicData.responses,undefined);assert.deepEqual(publicData.own.answers,{});assert(!JSON.stringify(publicData).includes('Deneme Misafiri'));assert(!JSON.stringify(publicData).includes('Deneme şarkı yanıtı'));
let privateData=await req(host);assert.equal(privateData.responses[0].answers.q1,'Deneme şarkı yanıtı');
own=await req(pub+'/social','POST',{guestToken:g.token,pollId:'p1',votes:['sat'],answers:{q1:'Güncellenen yanıt'}});assert.equal(own.totals.sun,0);assert.equal(own.totals.sat,1);
await req(host,'PATCH',{settings:{...settings,poll:{...settings.poll,closed:true}},version:1});
await req(pub+'/social','POST',{guestToken:g.token,pollId:'p1',votes:['sun'],answers:{}},400);
await req(pub+'/social','POST',{guestToken:g.token,pollId:'old',votes:['sat'],answers:{}},409);
await req(pub+'/social','POST',{guestToken:g.token,pollId:'p1',votes:['sat'],answers:{q1:'Kapalı oylamada soru yanıtı güncellenebilir'}});
await req(host,'PATCH',{settings,version:2});
const managed=await req('/api/mobile/events/'+a.manageToken);assert.equal(managed.coverId,'citrus');assert.equal(managed.guests.length,1);
fs.writeFileSync('../test-fixture.json',JSON.stringify({a,b,g},null,2));
console.log(`${checks} HTTP checks passed: template persistence, version conflict, validation, cross-event auth, anonymous auth, private answers, deduplicated voting, vote updates, poll closing, stale polls.`);
